export const actionTypes = {
    SET_USER_DATA: 'SET_USER_DATA',
    CLEAR_USER_DATA: 'CLEAR_USER_DATA',
    SET_LOGIN: 'SET_LOGIN',
    SAVE_DESIGN_REQUIREMENTS: 'SAVE_DESIGN_REQUIREMENTS',
    SAVE_ALL_DESIGN_REQUIREMENTS: 'SAVE_ALL_DESIGN_REQUIREMENTS',
    SHOW_AUTH_MODAL: 'SHOW_AUTH_MODAL',
}